// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_app_buildQueryVariables = Exact<{ [key: string]: never; }>;


export type starterkit_app_buildQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', buildGitCommit: string } };


export function $starterkit_app_build(opts?: { revalidate?: boolean }): starterkit_app_buildQuery {
	return $starterkit_gql_request(`query starterkit_app_build {
  admin {
    buildGitCommit
  }
}`, undefined, opts) as starterkit_app_buildQuery
}

}
