// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_app_signoutMutationVariables = Exact<{ [key: string]: never; }>;


export type starterkit_app_signoutMutation = { __typename?: 'Mutation', signOut: { __typename?: 'SignOutPayload', redirectUrl: string } };


export function $starterkit_app_signout(opts?: { revalidate?: boolean }): starterkit_app_signoutMutation {
	return $starterkit_gql_request(`mutation starterkit_app_signout {
  signOut {
    redirectUrl
  }
}`, undefined, opts) as starterkit_app_signoutMutation
}

}
