// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_app_viewerQueryVariables = Exact<{ [key: string]: never; }>;


export type starterkit_app_viewerQuery = { __typename?: 'Query', viewer: { __typename?: 'Viewer', role: ViewerRole, user?: { __typename?: 'User', id: number, email: string, name: string } | null } };


export function $starterkit_app_viewer(opts?: { revalidate?: boolean }): starterkit_app_viewerQuery {
	return $starterkit_gql_request(`query starterkit_app_viewer {
  viewer {
    role
    user {
      id
      email
      name
    }
  }
}`, undefined, opts) as starterkit_app_viewerQuery
}

}
