root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  delay = 500
  exclude_dir = ["tmp", "node_modules", "docs", "docker", "db", ".mam"]
  exclude_regex = ["_test.go", "generated.go"]
  include_ext = ["go", "graphqls", "html"]
  kill_delay = "2s"
  log = "build-errors.log"
  send_interrupt = true

[log]
  main_only = false

[misc]
  clean_on_exit = true
