// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package removeadmin_test

import (
	"context"
	"starterkit/internal/case/removeadmin"
	"starterkit/internal/db"
	"sync"
)

// Ensure, that EnvMock does implement removeadmin.Env.
// If this is not the case, regenerate this file with moq.
var _ removeadmin.Env = &EnvMock{}

// EnvMock is a mock implementation of removeadmin.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked removeadmin.Env
//		mockedEnv := &EnvMock{
//			CurrentUserIDFunc: func(ctx context.Context) *int64 {
//				panic("mock out the CurrentUserID method")
//			},
//			DBDeleteAdminFunc: func(ctx context.Context, userID int64) (int64, error) {
//				panic("mock out the DBDeleteAdmin method")
//			},
//			DBGetAdminByUserIDFunc: func(ctx context.Context, userID int64) (db.Admin, error) {
//				panic("mock out the DBGetAdminByUserID method")
//			},
//			MetricsIncreaseAdminChangedFunc: func(ctx context.Context, action string)  {
//				panic("mock out the MetricsIncreaseAdminChanged method")
//			},
//		}
//
//		// use mockedEnv in code that requires removeadmin.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentUserIDFunc mocks the CurrentUserID method.
	CurrentUserIDFunc func(ctx context.Context) *int64

	// DBDeleteAdminFunc mocks the DBDeleteAdmin method.
	DBDeleteAdminFunc func(ctx context.Context, userID int64) (int64, error)

	// DBGetAdminByUserIDFunc mocks the DBGetAdminByUserID method.
	DBGetAdminByUserIDFunc func(ctx context.Context, userID int64) (db.Admin, error)

	// MetricsIncreaseAdminChangedFunc mocks the MetricsIncreaseAdminChanged method.
	MetricsIncreaseAdminChangedFunc func(ctx context.Context, action string)

	// calls tracks calls to the methods.
	calls struct {
		// CurrentUserID holds details about calls to the CurrentUserID method.
		CurrentUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DBDeleteAdmin holds details about calls to the DBDeleteAdmin method.
		DBDeleteAdmin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// DBGetAdminByUserID holds details about calls to the DBGetAdminByUserID method.
		DBGetAdminByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// MetricsIncreaseAdminChanged holds details about calls to the MetricsIncreaseAdminChanged method.
		MetricsIncreaseAdminChanged []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Action is the action argument value.
			Action string
		}
	}
	lockCurrentUserID               sync.RWMutex
	lockDBDeleteAdmin               sync.RWMutex
	lockDBGetAdminByUserID          sync.RWMutex
	lockMetricsIncreaseAdminChanged sync.RWMutex
}

// CurrentUserID calls CurrentUserIDFunc.
func (mock *EnvMock) CurrentUserID(ctx context.Context) *int64 {
	if mock.CurrentUserIDFunc == nil {
		panic("EnvMock.CurrentUserIDFunc: method is nil but Env.CurrentUserID was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentUserID.Lock()
	mock.calls.CurrentUserID = append(mock.calls.CurrentUserID, callInfo)
	mock.lockCurrentUserID.Unlock()
	return mock.CurrentUserIDFunc(ctx)
}

// CurrentUserIDCalls gets all the calls that were made to CurrentUserID.
// Check the length with:
//
//	len(mockedEnv.CurrentUserIDCalls())
func (mock *EnvMock) CurrentUserIDCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentUserID.RLock()
	calls = mock.calls.CurrentUserID
	mock.lockCurrentUserID.RUnlock()
	return calls
}

// DBDeleteAdmin calls DBDeleteAdminFunc.
func (mock *EnvMock) DBDeleteAdmin(ctx context.Context, userID int64) (int64, error) {
	if mock.DBDeleteAdminFunc == nil {
		panic("EnvMock.DBDeleteAdminFunc: method is nil but Env.DBDeleteAdmin was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDBDeleteAdmin.Lock()
	mock.calls.DBDeleteAdmin = append(mock.calls.DBDeleteAdmin, callInfo)
	mock.lockDBDeleteAdmin.Unlock()
	return mock.DBDeleteAdminFunc(ctx, userID)
}

// DBDeleteAdminCalls gets all the calls that were made to DBDeleteAdmin.
// Check the length with:
//
//	len(mockedEnv.DBDeleteAdminCalls())
func (mock *EnvMock) DBDeleteAdminCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockDBDeleteAdmin.RLock()
	calls = mock.calls.DBDeleteAdmin
	mock.lockDBDeleteAdmin.RUnlock()
	return calls
}

// DBGetAdminByUserID calls DBGetAdminByUserIDFunc.
func (mock *EnvMock) DBGetAdminByUserID(ctx context.Context, userID int64) (db.Admin, error) {
	if mock.DBGetAdminByUserIDFunc == nil {
		panic("EnvMock.DBGetAdminByUserIDFunc: method is nil but Env.DBGetAdminByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDBGetAdminByUserID.Lock()
	mock.calls.DBGetAdminByUserID = append(mock.calls.DBGetAdminByUserID, callInfo)
	mock.lockDBGetAdminByUserID.Unlock()
	return mock.DBGetAdminByUserIDFunc(ctx, userID)
}

// DBGetAdminByUserIDCalls gets all the calls that were made to DBGetAdminByUserID.
// Check the length with:
//
//	len(mockedEnv.DBGetAdminByUserIDCalls())
func (mock *EnvMock) DBGetAdminByUserIDCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockDBGetAdminByUserID.RLock()
	calls = mock.calls.DBGetAdminByUserID
	mock.lockDBGetAdminByUserID.RUnlock()
	return calls
}

// MetricsIncreaseAdminChanged calls MetricsIncreaseAdminChangedFunc.
func (mock *EnvMock) MetricsIncreaseAdminChanged(ctx context.Context, action string) {
	if mock.MetricsIncreaseAdminChangedFunc == nil {
		panic("EnvMock.MetricsIncreaseAdminChangedFunc: method is nil but Env.MetricsIncreaseAdminChanged was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Action string
	}{
		Ctx:    ctx,
		Action: action,
	}
	mock.lockMetricsIncreaseAdminChanged.Lock()
	mock.calls.MetricsIncreaseAdminChanged = append(mock.calls.MetricsIncreaseAdminChanged, callInfo)
	mock.lockMetricsIncreaseAdminChanged.Unlock()
	mock.MetricsIncreaseAdminChangedFunc(ctx, action)
}

// MetricsIncreaseAdminChangedCalls gets all the calls that were made to MetricsIncreaseAdminChanged.
// Check the length with:
//
//	len(mockedEnv.MetricsIncreaseAdminChangedCalls())
func (mock *EnvMock) MetricsIncreaseAdminChangedCalls() []struct {
	Ctx    context.Context
	Action string
} {
	var calls []struct {
		Ctx    context.Context
		Action string
	}
	mock.lockMetricsIncreaseAdminChanged.RLock()
	calls = mock.calls.MetricsIncreaseAdminChanged
	mock.lockMetricsIncreaseAdminChanged.RUnlock()
	return calls
}
