// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package unbanuser_test

import (
	"context"
	"starterkit/internal/case/unbanuser"
	"sync"
)

// Ensure, that EnvMock does implement unbanuser.Env.
// If this is not the case, regenerate this file with moq.
var _ unbanuser.Env = &EnvMock{}

// EnvMock is a mock implementation of unbanuser.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked unbanuser.Env
//		mockedEnv := &EnvMock{
//			DBDeleteUserBanFunc: func(ctx context.Context, userID int64) error {
//				panic("mock out the DBDeleteUserBan method")
//			},
//		}
//
//		// use mockedEnv in code that requires unbanuser.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// DBDeleteUserBanFunc mocks the DBDeleteUserBan method.
	DBDeleteUserBanFunc func(ctx context.Context, userID int64) error

	// calls tracks calls to the methods.
	calls struct {
		// DBDeleteUserBan holds details about calls to the DBDeleteUserBan method.
		DBDeleteUserBan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
	}
	lockDBDeleteUserBan sync.RWMutex
}

// DBDeleteUserBan calls DBDeleteUserBanFunc.
func (mock *EnvMock) DBDeleteUserBan(ctx context.Context, userID int64) error {
	if mock.DBDeleteUserBanFunc == nil {
		panic("EnvMock.DBDeleteUserBanFunc: method is nil but Env.DBDeleteUserBan was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDBDeleteUserBan.Lock()
	mock.calls.DBDeleteUserBan = append(mock.calls.DBDeleteUserBan, callInfo)
	mock.lockDBDeleteUserBan.Unlock()
	return mock.DBDeleteUserBanFunc(ctx, userID)
}

// DBDeleteUserBanCalls gets all the calls that were made to DBDeleteUserBan.
// Check the length with:
//
//	len(mockedEnv.DBDeleteUserBanCalls())
func (mock *EnvMock) DBDeleteUserBanCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockDBDeleteUserBan.RLock()
	calls = mock.calls.DBDeleteUserBan
	mock.lockDBDeleteUserBan.RUnlock()
	return calls
}
