// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package signinbyoidc_test

import (
	"context"
	"starterkit/internal/case/signinbyoidc"
	"starterkit/internal/db"
	"sync"
	"time"
)

// Ensure, that EnvMock does implement signinbyoidc.Env.
// If this is not the case, regenerate this file with moq.
var _ signinbyoidc.Env = &EnvMock{}

// EnvMock is a mock implementation of signinbyoidc.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked signinbyoidc.Env
//		mockedEnv := &EnvMock{
//			BootstrapAdminEmailFunc: func() string {
//				panic("mock out the BootstrapAdminEmail method")
//			},
//			DBCountAdminsFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the DBCountAdmins method")
//			},
//			DBGetAdminByUserIDFunc: func(ctx context.Context, userID int64) (db.Admin, error) {
//				panic("mock out the DBGetAdminByUserID method")
//			},
//			DBInsertAdminFunc: func(ctx context.Context, arg db.DBInsertAdminParams) error {
//				panic("mock out the DBInsertAdmin method")
//			},
//			DBUpsertUserByOIDCFunc: func(ctx context.Context, arg db.DBUpsertUserByOIDCParams) (db.User, error) {
//				panic("mock out the DBUpsertUserByOIDC method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedEnv in code that requires signinbyoidc.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// BootstrapAdminEmailFunc mocks the BootstrapAdminEmail method.
	BootstrapAdminEmailFunc func() string

	// DBCountAdminsFunc mocks the DBCountAdmins method.
	DBCountAdminsFunc func(ctx context.Context) (int64, error)

	// DBGetAdminByUserIDFunc mocks the DBGetAdminByUserID method.
	DBGetAdminByUserIDFunc func(ctx context.Context, userID int64) (db.Admin, error)

	// DBInsertAdminFunc mocks the DBInsertAdmin method.
	DBInsertAdminFunc func(ctx context.Context, arg db.DBInsertAdminParams) error

	// DBUpsertUserByOIDCFunc mocks the DBUpsertUserByOIDC method.
	DBUpsertUserByOIDCFunc func(ctx context.Context, arg db.DBUpsertUserByOIDCParams) (db.User, error)

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// BootstrapAdminEmail holds details about calls to the BootstrapAdminEmail method.
		BootstrapAdminEmail []struct {
		}
		// DBCountAdmins holds details about calls to the DBCountAdmins method.
		DBCountAdmins []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DBGetAdminByUserID holds details about calls to the DBGetAdminByUserID method.
		DBGetAdminByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// DBInsertAdmin holds details about calls to the DBInsertAdmin method.
		DBInsertAdmin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DBInsertAdminParams
		}
		// DBUpsertUserByOIDC holds details about calls to the DBUpsertUserByOIDC method.
		DBUpsertUserByOIDC []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DBUpsertUserByOIDCParams
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockBootstrapAdminEmail sync.RWMutex
	lockDBCountAdmins       sync.RWMutex
	lockDBGetAdminByUserID  sync.RWMutex
	lockDBInsertAdmin       sync.RWMutex
	lockDBUpsertUserByOIDC  sync.RWMutex
	lockNow                 sync.RWMutex
}

// BootstrapAdminEmail calls BootstrapAdminEmailFunc.
func (mock *EnvMock) BootstrapAdminEmail() string {
	if mock.BootstrapAdminEmailFunc == nil {
		panic("EnvMock.BootstrapAdminEmailFunc: method is nil but Env.BootstrapAdminEmail was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBootstrapAdminEmail.Lock()
	mock.calls.BootstrapAdminEmail = append(mock.calls.BootstrapAdminEmail, callInfo)
	mock.lockBootstrapAdminEmail.Unlock()
	return mock.BootstrapAdminEmailFunc()
}

// BootstrapAdminEmailCalls gets all the calls that were made to BootstrapAdminEmail.
// Check the length with:
//
//	len(mockedEnv.BootstrapAdminEmailCalls())
func (mock *EnvMock) BootstrapAdminEmailCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBootstrapAdminEmail.RLock()
	calls = mock.calls.BootstrapAdminEmail
	mock.lockBootstrapAdminEmail.RUnlock()
	return calls
}

// DBCountAdmins calls DBCountAdminsFunc.
func (mock *EnvMock) DBCountAdmins(ctx context.Context) (int64, error) {
	if mock.DBCountAdminsFunc == nil {
		panic("EnvMock.DBCountAdminsFunc: method is nil but Env.DBCountAdmins was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDBCountAdmins.Lock()
	mock.calls.DBCountAdmins = append(mock.calls.DBCountAdmins, callInfo)
	mock.lockDBCountAdmins.Unlock()
	return mock.DBCountAdminsFunc(ctx)
}

// DBCountAdminsCalls gets all the calls that were made to DBCountAdmins.
// Check the length with:
//
//	len(mockedEnv.DBCountAdminsCalls())
func (mock *EnvMock) DBCountAdminsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDBCountAdmins.RLock()
	calls = mock.calls.DBCountAdmins
	mock.lockDBCountAdmins.RUnlock()
	return calls
}

// DBGetAdminByUserID calls DBGetAdminByUserIDFunc.
func (mock *EnvMock) DBGetAdminByUserID(ctx context.Context, userID int64) (db.Admin, error) {
	if mock.DBGetAdminByUserIDFunc == nil {
		panic("EnvMock.DBGetAdminByUserIDFunc: method is nil but Env.DBGetAdminByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDBGetAdminByUserID.Lock()
	mock.calls.DBGetAdminByUserID = append(mock.calls.DBGetAdminByUserID, callInfo)
	mock.lockDBGetAdminByUserID.Unlock()
	return mock.DBGetAdminByUserIDFunc(ctx, userID)
}

// DBGetAdminByUserIDCalls gets all the calls that were made to DBGetAdminByUserID.
// Check the length with:
//
//	len(mockedEnv.DBGetAdminByUserIDCalls())
func (mock *EnvMock) DBGetAdminByUserIDCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockDBGetAdminByUserID.RLock()
	calls = mock.calls.DBGetAdminByUserID
	mock.lockDBGetAdminByUserID.RUnlock()
	return calls
}

// DBInsertAdmin calls DBInsertAdminFunc.
func (mock *EnvMock) DBInsertAdmin(ctx context.Context, arg db.DBInsertAdminParams) error {
	if mock.DBInsertAdminFunc == nil {
		panic("EnvMock.DBInsertAdminFunc: method is nil but Env.DBInsertAdmin was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DBInsertAdminParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDBInsertAdmin.Lock()
	mock.calls.DBInsertAdmin = append(mock.calls.DBInsertAdmin, callInfo)
	mock.lockDBInsertAdmin.Unlock()
	return mock.DBInsertAdminFunc(ctx, arg)
}

// DBInsertAdminCalls gets all the calls that were made to DBInsertAdmin.
// Check the length with:
//
//	len(mockedEnv.DBInsertAdminCalls())
func (mock *EnvMock) DBInsertAdminCalls() []struct {
	Ctx context.Context
	Arg db.DBInsertAdminParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DBInsertAdminParams
	}
	mock.lockDBInsertAdmin.RLock()
	calls = mock.calls.DBInsertAdmin
	mock.lockDBInsertAdmin.RUnlock()
	return calls
}

// DBUpsertUserByOIDC calls DBUpsertUserByOIDCFunc.
func (mock *EnvMock) DBUpsertUserByOIDC(ctx context.Context, arg db.DBUpsertUserByOIDCParams) (db.User, error) {
	if mock.DBUpsertUserByOIDCFunc == nil {
		panic("EnvMock.DBUpsertUserByOIDCFunc: method is nil but Env.DBUpsertUserByOIDC was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DBUpsertUserByOIDCParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDBUpsertUserByOIDC.Lock()
	mock.calls.DBUpsertUserByOIDC = append(mock.calls.DBUpsertUserByOIDC, callInfo)
	mock.lockDBUpsertUserByOIDC.Unlock()
	return mock.DBUpsertUserByOIDCFunc(ctx, arg)
}

// DBUpsertUserByOIDCCalls gets all the calls that were made to DBUpsertUserByOIDC.
// Check the length with:
//
//	len(mockedEnv.DBUpsertUserByOIDCCalls())
func (mock *EnvMock) DBUpsertUserByOIDCCalls() []struct {
	Ctx context.Context
	Arg db.DBUpsertUserByOIDCParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DBUpsertUserByOIDCParams
	}
	mock.lockDBUpsertUserByOIDC.RLock()
	calls = mock.calls.DBUpsertUserByOIDC
	mock.lockDBUpsertUserByOIDC.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *EnvMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("EnvMock.NowFunc: method is nil but Env.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedEnv.NowCalls())
func (mock *EnvMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
