// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package listauditlog_test

import (
	"context"
	"starterkit/internal/case/listauditlog"
	"starterkit/internal/db"
	"sync"
)

// Ensure, that EnvMock does implement listauditlog.Env.
// If this is not the case, regenerate this file with moq.
var _ listauditlog.Env = &EnvMock{}

// EnvMock is a mock implementation of listauditlog.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked listauditlog.Env
//		mockedEnv := &EnvMock{
//			DBCountAuditLogFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the DBCountAuditLog method")
//			},
//			DBListAuditLogFunc: func(ctx context.Context, arg db.DBListAuditLogParams) ([]db.AuditLog, error) {
//				panic("mock out the DBListAuditLog method")
//			},
//		}
//
//		// use mockedEnv in code that requires listauditlog.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// DBCountAuditLogFunc mocks the DBCountAuditLog method.
	DBCountAuditLogFunc func(ctx context.Context) (int64, error)

	// DBListAuditLogFunc mocks the DBListAuditLog method.
	DBListAuditLogFunc func(ctx context.Context, arg db.DBListAuditLogParams) ([]db.AuditLog, error)

	// calls tracks calls to the methods.
	calls struct {
		// DBCountAuditLog holds details about calls to the DBCountAuditLog method.
		DBCountAuditLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DBListAuditLog holds details about calls to the DBListAuditLog method.
		DBListAuditLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DBListAuditLogParams
		}
	}
	lockDBCountAuditLog sync.RWMutex
	lockDBListAuditLog  sync.RWMutex
}

// DBCountAuditLog calls DBCountAuditLogFunc.
func (mock *EnvMock) DBCountAuditLog(ctx context.Context) (int64, error) {
	if mock.DBCountAuditLogFunc == nil {
		panic("EnvMock.DBCountAuditLogFunc: method is nil but Env.DBCountAuditLog was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDBCountAuditLog.Lock()
	mock.calls.DBCountAuditLog = append(mock.calls.DBCountAuditLog, callInfo)
	mock.lockDBCountAuditLog.Unlock()
	return mock.DBCountAuditLogFunc(ctx)
}

// DBCountAuditLogCalls gets all the calls that were made to DBCountAuditLog.
// Check the length with:
//
//	len(mockedEnv.DBCountAuditLogCalls())
func (mock *EnvMock) DBCountAuditLogCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDBCountAuditLog.RLock()
	calls = mock.calls.DBCountAuditLog
	mock.lockDBCountAuditLog.RUnlock()
	return calls
}

// DBListAuditLog calls DBListAuditLogFunc.
func (mock *EnvMock) DBListAuditLog(ctx context.Context, arg db.DBListAuditLogParams) ([]db.AuditLog, error) {
	if mock.DBListAuditLogFunc == nil {
		panic("EnvMock.DBListAuditLogFunc: method is nil but Env.DBListAuditLog was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DBListAuditLogParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDBListAuditLog.Lock()
	mock.calls.DBListAuditLog = append(mock.calls.DBListAuditLog, callInfo)
	mock.lockDBListAuditLog.Unlock()
	return mock.DBListAuditLogFunc(ctx, arg)
}

// DBListAuditLogCalls gets all the calls that were made to DBListAuditLog.
// Check the length with:
//
//	len(mockedEnv.DBListAuditLogCalls())
func (mock *EnvMock) DBListAuditLogCalls() []struct {
	Ctx context.Context
	Arg db.DBListAuditLogParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DBListAuditLogParams
	}
	mock.lockDBListAuditLog.RLock()
	calls = mock.calls.DBListAuditLog
	mock.lockDBListAuditLog.RUnlock()
	return calls
}
