// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package makeadmin_test

import (
	"context"
	"starterkit/internal/case/makeadmin"
	"starterkit/internal/db"
	"sync"
	"time"
)

// Ensure, that EnvMock does implement makeadmin.Env.
// If this is not the case, regenerate this file with moq.
var _ makeadmin.Env = &EnvMock{}

// EnvMock is a mock implementation of makeadmin.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked makeadmin.Env
//		mockedEnv := &EnvMock{
//			DBGetAdminUserByIDFunc: func(ctx context.Context, id int64) (db.DBGetAdminUserByIDRow, error) {
//				panic("mock out the DBGetAdminUserByID method")
//			},
//			DBInsertAdminFunc: func(ctx context.Context, arg db.DBInsertAdminParams) error {
//				panic("mock out the DBInsertAdmin method")
//			},
//			MetricsIncreaseAdminChangedFunc: func(ctx context.Context, action string)  {
//				panic("mock out the MetricsIncreaseAdminChanged method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedEnv in code that requires makeadmin.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// DBGetAdminUserByIDFunc mocks the DBGetAdminUserByID method.
	DBGetAdminUserByIDFunc func(ctx context.Context, id int64) (db.DBGetAdminUserByIDRow, error)

	// DBInsertAdminFunc mocks the DBInsertAdmin method.
	DBInsertAdminFunc func(ctx context.Context, arg db.DBInsertAdminParams) error

	// MetricsIncreaseAdminChangedFunc mocks the MetricsIncreaseAdminChanged method.
	MetricsIncreaseAdminChangedFunc func(ctx context.Context, action string)

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// DBGetAdminUserByID holds details about calls to the DBGetAdminUserByID method.
		DBGetAdminUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DBInsertAdmin holds details about calls to the DBInsertAdmin method.
		DBInsertAdmin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DBInsertAdminParams
		}
		// MetricsIncreaseAdminChanged holds details about calls to the MetricsIncreaseAdminChanged method.
		MetricsIncreaseAdminChanged []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Action is the action argument value.
			Action string
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockDBGetAdminUserByID          sync.RWMutex
	lockDBInsertAdmin               sync.RWMutex
	lockMetricsIncreaseAdminChanged sync.RWMutex
	lockNow                         sync.RWMutex
}

// DBGetAdminUserByID calls DBGetAdminUserByIDFunc.
func (mock *EnvMock) DBGetAdminUserByID(ctx context.Context, id int64) (db.DBGetAdminUserByIDRow, error) {
	if mock.DBGetAdminUserByIDFunc == nil {
		panic("EnvMock.DBGetAdminUserByIDFunc: method is nil but Env.DBGetAdminUserByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDBGetAdminUserByID.Lock()
	mock.calls.DBGetAdminUserByID = append(mock.calls.DBGetAdminUserByID, callInfo)
	mock.lockDBGetAdminUserByID.Unlock()
	return mock.DBGetAdminUserByIDFunc(ctx, id)
}

// DBGetAdminUserByIDCalls gets all the calls that were made to DBGetAdminUserByID.
// Check the length with:
//
//	len(mockedEnv.DBGetAdminUserByIDCalls())
func (mock *EnvMock) DBGetAdminUserByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDBGetAdminUserByID.RLock()
	calls = mock.calls.DBGetAdminUserByID
	mock.lockDBGetAdminUserByID.RUnlock()
	return calls
}

// DBInsertAdmin calls DBInsertAdminFunc.
func (mock *EnvMock) DBInsertAdmin(ctx context.Context, arg db.DBInsertAdminParams) error {
	if mock.DBInsertAdminFunc == nil {
		panic("EnvMock.DBInsertAdminFunc: method is nil but Env.DBInsertAdmin was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DBInsertAdminParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDBInsertAdmin.Lock()
	mock.calls.DBInsertAdmin = append(mock.calls.DBInsertAdmin, callInfo)
	mock.lockDBInsertAdmin.Unlock()
	return mock.DBInsertAdminFunc(ctx, arg)
}

// DBInsertAdminCalls gets all the calls that were made to DBInsertAdmin.
// Check the length with:
//
//	len(mockedEnv.DBInsertAdminCalls())
func (mock *EnvMock) DBInsertAdminCalls() []struct {
	Ctx context.Context
	Arg db.DBInsertAdminParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DBInsertAdminParams
	}
	mock.lockDBInsertAdmin.RLock()
	calls = mock.calls.DBInsertAdmin
	mock.lockDBInsertAdmin.RUnlock()
	return calls
}

// MetricsIncreaseAdminChanged calls MetricsIncreaseAdminChangedFunc.
func (mock *EnvMock) MetricsIncreaseAdminChanged(ctx context.Context, action string) {
	if mock.MetricsIncreaseAdminChangedFunc == nil {
		panic("EnvMock.MetricsIncreaseAdminChangedFunc: method is nil but Env.MetricsIncreaseAdminChanged was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Action string
	}{
		Ctx:    ctx,
		Action: action,
	}
	mock.lockMetricsIncreaseAdminChanged.Lock()
	mock.calls.MetricsIncreaseAdminChanged = append(mock.calls.MetricsIncreaseAdminChanged, callInfo)
	mock.lockMetricsIncreaseAdminChanged.Unlock()
	mock.MetricsIncreaseAdminChangedFunc(ctx, action)
}

// MetricsIncreaseAdminChangedCalls gets all the calls that were made to MetricsIncreaseAdminChanged.
// Check the length with:
//
//	len(mockedEnv.MetricsIncreaseAdminChangedCalls())
func (mock *EnvMock) MetricsIncreaseAdminChangedCalls() []struct {
	Ctx    context.Context
	Action string
} {
	var calls []struct {
		Ctx    context.Context
		Action string
	}
	mock.lockMetricsIncreaseAdminChanged.RLock()
	calls = mock.calls.MetricsIncreaseAdminChanged
	mock.lockMetricsIncreaseAdminChanged.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *EnvMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("EnvMock.NowFunc: method is nil but Env.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedEnv.NowCalls())
func (mock *EnvMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
