// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_users_catalog_listQueryVariables = Exact<{ [key: string]: never; }>;


export type starterkit_users_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', users: { __typename?: 'UsersConnection', totalCount: number, nodes: Array<{ __typename?: 'AdminUser', id: number, email: string, name: string, isAdmin: boolean, banReason: string, createdAt: { __typename?: 'Timestamp', formatted: string }, lastSignInAt?: { __typename?: 'Timestamp', formatted: string } | null }> } } };


export function $starterkit_users_catalog_list(opts?: { revalidate?: boolean }): starterkit_users_catalog_listQuery {
	return $starterkit_gql_request(`query starterkit_users_catalog_list {
  admin {
    users {
      totalCount
      nodes {
        id
        email
        name
        createdAt {
          formatted(layout: "2006-01-02 15:04")
        }
        lastSignInAt {
          formatted(layout: "2006-01-02 15:04")
        }
        isAdmin
        banReason
      }
    }
  }
}`, undefined, opts) as starterkit_users_catalog_listQuery
}

}
