// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package purgeauditlog_test

import (
	"context"
	"starterkit/internal/case/purgeauditlog"
	"starterkit/internal/dbtime"
	"sync"
	"time"
)

// Ensure, that EnvMock does implement purgeauditlog.Env.
// If this is not the case, regenerate this file with moq.
var _ purgeauditlog.Env = &EnvMock{}

// EnvMock is a mock implementation of purgeauditlog.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked purgeauditlog.Env
//		mockedEnv := &EnvMock{
//			AuditRetentionFunc: func() time.Duration {
//				panic("mock out the AuditRetention method")
//			},
//			DBDeleteAuditLogBeforeFunc: func(ctx context.Context, before dbtime.Stamp) error {
//				panic("mock out the DBDeleteAuditLogBefore method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedEnv in code that requires purgeauditlog.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// AuditRetentionFunc mocks the AuditRetention method.
	AuditRetentionFunc func() time.Duration

	// DBDeleteAuditLogBeforeFunc mocks the DBDeleteAuditLogBefore method.
	DBDeleteAuditLogBeforeFunc func(ctx context.Context, before dbtime.Stamp) error

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// AuditRetention holds details about calls to the AuditRetention method.
		AuditRetention []struct {
		}
		// DBDeleteAuditLogBefore holds details about calls to the DBDeleteAuditLogBefore method.
		DBDeleteAuditLogBefore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Before is the before argument value.
			Before dbtime.Stamp
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockAuditRetention         sync.RWMutex
	lockDBDeleteAuditLogBefore sync.RWMutex
	lockNow                    sync.RWMutex
}

// AuditRetention calls AuditRetentionFunc.
func (mock *EnvMock) AuditRetention() time.Duration {
	if mock.AuditRetentionFunc == nil {
		panic("EnvMock.AuditRetentionFunc: method is nil but Env.AuditRetention was just called")
	}
	callInfo := struct {
	}{}
	mock.lockAuditRetention.Lock()
	mock.calls.AuditRetention = append(mock.calls.AuditRetention, callInfo)
	mock.lockAuditRetention.Unlock()
	return mock.AuditRetentionFunc()
}

// AuditRetentionCalls gets all the calls that were made to AuditRetention.
// Check the length with:
//
//	len(mockedEnv.AuditRetentionCalls())
func (mock *EnvMock) AuditRetentionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAuditRetention.RLock()
	calls = mock.calls.AuditRetention
	mock.lockAuditRetention.RUnlock()
	return calls
}

// DBDeleteAuditLogBefore calls DBDeleteAuditLogBeforeFunc.
func (mock *EnvMock) DBDeleteAuditLogBefore(ctx context.Context, before dbtime.Stamp) error {
	if mock.DBDeleteAuditLogBeforeFunc == nil {
		panic("EnvMock.DBDeleteAuditLogBeforeFunc: method is nil but Env.DBDeleteAuditLogBefore was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Before dbtime.Stamp
	}{
		Ctx:    ctx,
		Before: before,
	}
	mock.lockDBDeleteAuditLogBefore.Lock()
	mock.calls.DBDeleteAuditLogBefore = append(mock.calls.DBDeleteAuditLogBefore, callInfo)
	mock.lockDBDeleteAuditLogBefore.Unlock()
	return mock.DBDeleteAuditLogBeforeFunc(ctx, before)
}

// DBDeleteAuditLogBeforeCalls gets all the calls that were made to DBDeleteAuditLogBefore.
// Check the length with:
//
//	len(mockedEnv.DBDeleteAuditLogBeforeCalls())
func (mock *EnvMock) DBDeleteAuditLogBeforeCalls() []struct {
	Ctx    context.Context
	Before dbtime.Stamp
} {
	var calls []struct {
		Ctx    context.Context
		Before dbtime.Stamp
	}
	mock.lockDBDeleteAuditLogBefore.RLock()
	calls = mock.calls.DBDeleteAuditLogBefore
	mock.lockDBDeleteAuditLogBefore.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *EnvMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("EnvMock.NowFunc: method is nil but Env.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedEnv.NowCalls())
func (mock *EnvMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
