// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package notifyuserbanned_test

import (
	"context"
	"starterkit/internal/case/notifyuserbanned"
	"starterkit/internal/db"
	"starterkit/internal/notifier"
	"sync"
)

// Ensure, that EnvMock does implement notifyuserbanned.Env.
// If this is not the case, regenerate this file with moq.
var _ notifyuserbanned.Env = &EnvMock{}

// EnvMock is a mock implementation of notifyuserbanned.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked notifyuserbanned.Env
//		mockedEnv := &EnvMock{
//			DBGetUserBanFunc: func(ctx context.Context, userID int64) (db.UserBan, error) {
//				panic("mock out the DBGetUserBan method")
//			},
//			DBGetUserByIDFunc: func(ctx context.Context, id int64) (db.User, error) {
//				panic("mock out the DBGetUserByID method")
//			},
//			NotifyUserBannedFunc: func(ctx context.Context, to notifier.Address, reason string) error {
//				panic("mock out the NotifyUserBanned method")
//			},
//		}
//
//		// use mockedEnv in code that requires notifyuserbanned.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// DBGetUserBanFunc mocks the DBGetUserBan method.
	DBGetUserBanFunc func(ctx context.Context, userID int64) (db.UserBan, error)

	// DBGetUserByIDFunc mocks the DBGetUserByID method.
	DBGetUserByIDFunc func(ctx context.Context, id int64) (db.User, error)

	// NotifyUserBannedFunc mocks the NotifyUserBanned method.
	NotifyUserBannedFunc func(ctx context.Context, to notifier.Address, reason string) error

	// calls tracks calls to the methods.
	calls struct {
		// DBGetUserBan holds details about calls to the DBGetUserBan method.
		DBGetUserBan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// DBGetUserByID holds details about calls to the DBGetUserByID method.
		DBGetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// NotifyUserBanned holds details about calls to the NotifyUserBanned method.
		NotifyUserBanned []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// To is the to argument value.
			To notifier.Address
			// Reason is the reason argument value.
			Reason string
		}
	}
	lockDBGetUserBan     sync.RWMutex
	lockDBGetUserByID    sync.RWMutex
	lockNotifyUserBanned sync.RWMutex
}

// DBGetUserBan calls DBGetUserBanFunc.
func (mock *EnvMock) DBGetUserBan(ctx context.Context, userID int64) (db.UserBan, error) {
	if mock.DBGetUserBanFunc == nil {
		panic("EnvMock.DBGetUserBanFunc: method is nil but Env.DBGetUserBan was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDBGetUserBan.Lock()
	mock.calls.DBGetUserBan = append(mock.calls.DBGetUserBan, callInfo)
	mock.lockDBGetUserBan.Unlock()
	return mock.DBGetUserBanFunc(ctx, userID)
}

// DBGetUserBanCalls gets all the calls that were made to DBGetUserBan.
// Check the length with:
//
//	len(mockedEnv.DBGetUserBanCalls())
func (mock *EnvMock) DBGetUserBanCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockDBGetUserBan.RLock()
	calls = mock.calls.DBGetUserBan
	mock.lockDBGetUserBan.RUnlock()
	return calls
}

// DBGetUserByID calls DBGetUserByIDFunc.
func (mock *EnvMock) DBGetUserByID(ctx context.Context, id int64) (db.User, error) {
	if mock.DBGetUserByIDFunc == nil {
		panic("EnvMock.DBGetUserByIDFunc: method is nil but Env.DBGetUserByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDBGetUserByID.Lock()
	mock.calls.DBGetUserByID = append(mock.calls.DBGetUserByID, callInfo)
	mock.lockDBGetUserByID.Unlock()
	return mock.DBGetUserByIDFunc(ctx, id)
}

// DBGetUserByIDCalls gets all the calls that were made to DBGetUserByID.
// Check the length with:
//
//	len(mockedEnv.DBGetUserByIDCalls())
func (mock *EnvMock) DBGetUserByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDBGetUserByID.RLock()
	calls = mock.calls.DBGetUserByID
	mock.lockDBGetUserByID.RUnlock()
	return calls
}

// NotifyUserBanned calls NotifyUserBannedFunc.
func (mock *EnvMock) NotifyUserBanned(ctx context.Context, to notifier.Address, reason string) error {
	if mock.NotifyUserBannedFunc == nil {
		panic("EnvMock.NotifyUserBannedFunc: method is nil but Env.NotifyUserBanned was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		To     notifier.Address
		Reason string
	}{
		Ctx:    ctx,
		To:     to,
		Reason: reason,
	}
	mock.lockNotifyUserBanned.Lock()
	mock.calls.NotifyUserBanned = append(mock.calls.NotifyUserBanned, callInfo)
	mock.lockNotifyUserBanned.Unlock()
	return mock.NotifyUserBannedFunc(ctx, to, reason)
}

// NotifyUserBannedCalls gets all the calls that were made to NotifyUserBanned.
// Check the length with:
//
//	len(mockedEnv.NotifyUserBannedCalls())
func (mock *EnvMock) NotifyUserBannedCalls() []struct {
	Ctx    context.Context
	To     notifier.Address
	Reason string
} {
	var calls []struct {
		Ctx    context.Context
		To     notifier.Address
		Reason string
	}
	mock.lockNotifyUserBanned.RLock()
	calls = mock.calls.NotifyUserBanned
	mock.lockNotifyUserBanned.RUnlock()
	return calls
}
