// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"starterkit/internal/db"
	"strconv"
)

type BanUserOrErrorPayload interface {
	IsBanUserOrErrorPayload()
}

type MakeAdminOrErrorPayload interface {
	IsMakeAdminOrErrorPayload()
}

type RemoveAdminOrErrorPayload interface {
	IsRemoveAdminOrErrorPayload()
}

type UnbanUserOrErrorPayload interface {
	IsUnbanUserOrErrorPayload()
}

type AdminsConnection struct {
	TotalCount int64                `json:"totalCount"`
	Nodes      []db.DBListAdminsRow `json:"nodes"`
}

type BanUserInput struct {
	UserID int64  `json:"userId"`
	Reason string `json:"reason"`
}

type BanUserPayload struct {
	UserID int64 `json:"userId"`
}

func (BanUserPayload) IsBanUserOrErrorPayload() {}

type ErrorPayload struct {
	Message  string         `json:"message"`
	ByFields []FieldMessage `json:"byFields"`
}

func (ErrorPayload) IsBanUserOrErrorPayload() {}

func (ErrorPayload) IsUnbanUserOrErrorPayload() {}

func (ErrorPayload) IsMakeAdminOrErrorPayload() {}

func (ErrorPayload) IsRemoveAdminOrErrorPayload() {}

type FieldMessage struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type MakeAdminInput struct {
	UserID int64 `json:"userId"`
}

type MakeAdminPayload struct {
	UserID int64 `json:"userId"`
}

func (MakeAdminPayload) IsMakeAdminOrErrorPayload() {}

type Mutation struct {
}

type Query struct {
}

type RemoveAdminInput struct {
	UserID int64 `json:"userId"`
}

type RemoveAdminPayload struct {
	UserID int64 `json:"userId"`
}

func (RemoveAdminPayload) IsRemoveAdminOrErrorPayload() {}

type SignOutPayload struct {
	RedirectURL string `json:"redirectUrl"`
}

type UnbanUserInput struct {
	UserID int64 `json:"userId"`
}

type UnbanUserPayload struct {
	UserID int64 `json:"userId"`
}

func (UnbanUserPayload) IsUnbanUserOrErrorPayload() {}

type UsersConnection struct {
	TotalCount int64               `json:"totalCount"`
	Nodes      []db.DBListUsersRow `json:"nodes"`
}

type ViewerRole string

const (
	ViewerRoleAdmin ViewerRole = "ADMIN"
	ViewerRoleUser  ViewerRole = "USER"
	ViewerRoleGuest ViewerRole = "GUEST"
)

var AllViewerRole = []ViewerRole{
	ViewerRoleAdmin,
	ViewerRoleUser,
	ViewerRoleGuest,
}

func (e ViewerRole) IsValid() bool {
	switch e {
	case ViewerRoleAdmin, ViewerRoleUser, ViewerRoleGuest:
		return true
	}
	return false
}

func (e ViewerRole) String() string {
	return string(e)
}

func (e *ViewerRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ViewerRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ViewerRole", str)
	}
	return nil
}

func (e ViewerRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ViewerRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ViewerRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
