// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package banuser_test

import (
	"context"
	"starterkit/internal/case/banuser"
	"starterkit/internal/db"
	"sync"
	"time"
)

// Ensure, that EnvMock does implement banuser.Env.
// If this is not the case, regenerate this file with moq.
var _ banuser.Env = &EnvMock{}

// EnvMock is a mock implementation of banuser.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked banuser.Env
//		mockedEnv := &EnvMock{
//			CurrentUserIDFunc: func(ctx context.Context) *int64 {
//				panic("mock out the CurrentUserID method")
//			},
//			DBGetUserByIDFunc: func(ctx context.Context, id int64) (db.User, error) {
//				panic("mock out the DBGetUserByID method")
//			},
//			DBInsertUserBanFunc: func(ctx context.Context, arg db.DBInsertUserBanParams) (db.UserBan, error) {
//				panic("mock out the DBInsertUserBan method")
//			},
//			EnqueueUserBannedNoticeFunc: func(ctx context.Context, userID int64) error {
//				panic("mock out the EnqueueUserBannedNotice method")
//			},
//			MetricsIncreaseUserBannedFunc: func(ctx context.Context)  {
//				panic("mock out the MetricsIncreaseUserBanned method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//		}
//
//		// use mockedEnv in code that requires banuser.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentUserIDFunc mocks the CurrentUserID method.
	CurrentUserIDFunc func(ctx context.Context) *int64

	// DBGetUserByIDFunc mocks the DBGetUserByID method.
	DBGetUserByIDFunc func(ctx context.Context, id int64) (db.User, error)

	// DBInsertUserBanFunc mocks the DBInsertUserBan method.
	DBInsertUserBanFunc func(ctx context.Context, arg db.DBInsertUserBanParams) (db.UserBan, error)

	// EnqueueUserBannedNoticeFunc mocks the EnqueueUserBannedNotice method.
	EnqueueUserBannedNoticeFunc func(ctx context.Context, userID int64) error

	// MetricsIncreaseUserBannedFunc mocks the MetricsIncreaseUserBanned method.
	MetricsIncreaseUserBannedFunc func(ctx context.Context)

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// calls tracks calls to the methods.
	calls struct {
		// CurrentUserID holds details about calls to the CurrentUserID method.
		CurrentUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DBGetUserByID holds details about calls to the DBGetUserByID method.
		DBGetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// DBInsertUserBan holds details about calls to the DBInsertUserBan method.
		DBInsertUserBan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DBInsertUserBanParams
		}
		// EnqueueUserBannedNotice holds details about calls to the EnqueueUserBannedNotice method.
		EnqueueUserBannedNotice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// MetricsIncreaseUserBanned holds details about calls to the MetricsIncreaseUserBanned method.
		MetricsIncreaseUserBanned []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
	}
	lockCurrentUserID             sync.RWMutex
	lockDBGetUserByID             sync.RWMutex
	lockDBInsertUserBan           sync.RWMutex
	lockEnqueueUserBannedNotice   sync.RWMutex
	lockMetricsIncreaseUserBanned sync.RWMutex
	lockNow                       sync.RWMutex
}

// CurrentUserID calls CurrentUserIDFunc.
func (mock *EnvMock) CurrentUserID(ctx context.Context) *int64 {
	if mock.CurrentUserIDFunc == nil {
		panic("EnvMock.CurrentUserIDFunc: method is nil but Env.CurrentUserID was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentUserID.Lock()
	mock.calls.CurrentUserID = append(mock.calls.CurrentUserID, callInfo)
	mock.lockCurrentUserID.Unlock()
	return mock.CurrentUserIDFunc(ctx)
}

// CurrentUserIDCalls gets all the calls that were made to CurrentUserID.
// Check the length with:
//
//	len(mockedEnv.CurrentUserIDCalls())
func (mock *EnvMock) CurrentUserIDCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentUserID.RLock()
	calls = mock.calls.CurrentUserID
	mock.lockCurrentUserID.RUnlock()
	return calls
}

// DBGetUserByID calls DBGetUserByIDFunc.
func (mock *EnvMock) DBGetUserByID(ctx context.Context, id int64) (db.User, error) {
	if mock.DBGetUserByIDFunc == nil {
		panic("EnvMock.DBGetUserByIDFunc: method is nil but Env.DBGetUserByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDBGetUserByID.Lock()
	mock.calls.DBGetUserByID = append(mock.calls.DBGetUserByID, callInfo)
	mock.lockDBGetUserByID.Unlock()
	return mock.DBGetUserByIDFunc(ctx, id)
}

// DBGetUserByIDCalls gets all the calls that were made to DBGetUserByID.
// Check the length with:
//
//	len(mockedEnv.DBGetUserByIDCalls())
func (mock *EnvMock) DBGetUserByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDBGetUserByID.RLock()
	calls = mock.calls.DBGetUserByID
	mock.lockDBGetUserByID.RUnlock()
	return calls
}

// DBInsertUserBan calls DBInsertUserBanFunc.
func (mock *EnvMock) DBInsertUserBan(ctx context.Context, arg db.DBInsertUserBanParams) (db.UserBan, error) {
	if mock.DBInsertUserBanFunc == nil {
		panic("EnvMock.DBInsertUserBanFunc: method is nil but Env.DBInsertUserBan was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DBInsertUserBanParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDBInsertUserBan.Lock()
	mock.calls.DBInsertUserBan = append(mock.calls.DBInsertUserBan, callInfo)
	mock.lockDBInsertUserBan.Unlock()
	return mock.DBInsertUserBanFunc(ctx, arg)
}

// DBInsertUserBanCalls gets all the calls that were made to DBInsertUserBan.
// Check the length with:
//
//	len(mockedEnv.DBInsertUserBanCalls())
func (mock *EnvMock) DBInsertUserBanCalls() []struct {
	Ctx context.Context
	Arg db.DBInsertUserBanParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DBInsertUserBanParams
	}
	mock.lockDBInsertUserBan.RLock()
	calls = mock.calls.DBInsertUserBan
	mock.lockDBInsertUserBan.RUnlock()
	return calls
}

// EnqueueUserBannedNotice calls EnqueueUserBannedNoticeFunc.
func (mock *EnvMock) EnqueueUserBannedNotice(ctx context.Context, userID int64) error {
	if mock.EnqueueUserBannedNoticeFunc == nil {
		panic("EnvMock.EnqueueUserBannedNoticeFunc: method is nil but Env.EnqueueUserBannedNotice was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockEnqueueUserBannedNotice.Lock()
	mock.calls.EnqueueUserBannedNotice = append(mock.calls.EnqueueUserBannedNotice, callInfo)
	mock.lockEnqueueUserBannedNotice.Unlock()
	return mock.EnqueueUserBannedNoticeFunc(ctx, userID)
}

// EnqueueUserBannedNoticeCalls gets all the calls that were made to EnqueueUserBannedNotice.
// Check the length with:
//
//	len(mockedEnv.EnqueueUserBannedNoticeCalls())
func (mock *EnvMock) EnqueueUserBannedNoticeCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockEnqueueUserBannedNotice.RLock()
	calls = mock.calls.EnqueueUserBannedNotice
	mock.lockEnqueueUserBannedNotice.RUnlock()
	return calls
}

// MetricsIncreaseUserBanned calls MetricsIncreaseUserBannedFunc.
func (mock *EnvMock) MetricsIncreaseUserBanned(ctx context.Context) {
	if mock.MetricsIncreaseUserBannedFunc == nil {
		panic("EnvMock.MetricsIncreaseUserBannedFunc: method is nil but Env.MetricsIncreaseUserBanned was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockMetricsIncreaseUserBanned.Lock()
	mock.calls.MetricsIncreaseUserBanned = append(mock.calls.MetricsIncreaseUserBanned, callInfo)
	mock.lockMetricsIncreaseUserBanned.Unlock()
	mock.MetricsIncreaseUserBannedFunc(ctx)
}

// MetricsIncreaseUserBannedCalls gets all the calls that were made to MetricsIncreaseUserBanned.
// Check the length with:
//
//	len(mockedEnv.MetricsIncreaseUserBannedCalls())
func (mock *EnvMock) MetricsIncreaseUserBannedCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockMetricsIncreaseUserBanned.RLock()
	calls = mock.calls.MetricsIncreaseUserBanned
	mock.lockMetricsIncreaseUserBanned.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *EnvMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("EnvMock.NowFunc: method is nil but Env.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedEnv.NowCalls())
func (mock *EnvMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}
