// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_auditlog_listQueryVariables = Exact<{
  limit: Scalars['Int64']['input'];
  before?: InputMaybe<Scalars['Int64']['input']>;
}>;


export type starterkit_auditlog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', auditLog: { __typename?: 'AuditLogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasNextPage: boolean, endCursor?: number | null }, nodes: Array<{ __typename?: 'AuditLogEntry', id: number, action: string, email: string, detail: string, ip: string, createdAt: { __typename?: 'Timestamp', formatted: string } }> } } };


export function $starterkit_auditlog_list(variables: starterkit_auditlog_listQueryVariables, opts?: { revalidate?: boolean }): starterkit_auditlog_listQuery {
	return $starterkit_gql_request(`query starterkit_auditlog_list(\u0024limit: Int64!, \u0024before: Int64) {
  admin {
    auditLog(limit: \u0024limit, before: \u0024before) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        id
        action
        email
        detail
        ip
        createdAt {
          formatted(layout: "2006-01-02 15:04:05")
        }
      }
    }
  }
}`, variables, opts) as starterkit_auditlog_listQuery
}

}
