// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' \u0024fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  Int64: { input: number; output: number; }
};

export type Admin = {
  __typename?: 'Admin';
  createdAt: Timestamp;
  email: Scalars['String']['output'];
  name: Scalars['String']['output'];
  userId: Scalars['Int64']['output'];
};

export type AdminMutation = {
  __typename?: 'AdminMutation';
  banUser: BanUserOrErrorPayload;
  makeAdmin: MakeAdminOrErrorPayload;
  removeAdmin: RemoveAdminOrErrorPayload;
  unbanUser: UnbanUserOrErrorPayload;
};


export type AdminMutationbanUserArgs = {
  input: BanUserInput;
};


export type AdminMutationmakeAdminArgs = {
  input: MakeAdminInput;
};


export type AdminMutationremoveAdminArgs = {
  input: RemoveAdminInput;
};


export type AdminMutationunbanUserArgs = {
  input: UnbanUserInput;
};

export type AdminQuery = {
  __typename?: 'AdminQuery';
  admins: AdminsConnection;
  auditLog: AuditLogConnection;
  buildGitCommit: Scalars['String']['output'];
  user?: Maybe<AdminUser>;
  users: UsersConnection;
};


export type AdminQueryauditLogArgs = {
  before?: InputMaybe<Scalars['Int64']['input']>;
  limit?: Scalars['Int64']['input'];
};


export type AdminQueryuserArgs = {
  id: Scalars['Int64']['input'];
};

export type AdminUser = {
  __typename?: 'AdminUser';
  banReason: Scalars['String']['output'];
  createdAt: Timestamp;
  email: Scalars['String']['output'];
  id: Scalars['Int64']['output'];
  isAdmin: Scalars['Boolean']['output'];
  lastSignInAt?: Maybe<Timestamp>;
  name: Scalars['String']['output'];
};

export type AdminsConnection = {
  __typename?: 'AdminsConnection';
  nodes: Array<Admin>;
  totalCount: Scalars['Int64']['output'];
};

export type AuditLogConnection = {
  __typename?: 'AuditLogConnection';
  nodes: Array<AuditLogEntry>;
  pageInfo: PageInfo;
  totalCount: Scalars['Int64']['output'];
};

export type AuditLogEntry = {
  __typename?: 'AuditLogEntry';
  action: Scalars['String']['output'];
  createdAt: Timestamp;
  detail: Scalars['String']['output'];
  email: Scalars['String']['output'];
  id: Scalars['Int64']['output'];
  ip: Scalars['String']['output'];
  userId?: Maybe<Scalars['Int64']['output']>;
};

export type BanUserInput = {
  reason: Scalars['String']['input'];
  userId: Scalars['Int64']['input'];
};

export type BanUserOrErrorPayload = BanUserPayload | ErrorPayload;

export type BanUserPayload = {
  __typename?: 'BanUserPayload';
  userId: Scalars['Int64']['output'];
};

export type ErrorPayload = {
  __typename?: 'ErrorPayload';
  byFields: Array<FieldMessage>;
  message: Scalars['String']['output'];
};

export type FieldMessage = {
  __typename?: 'FieldMessage';
  name: Scalars['String']['output'];
  value: Scalars['String']['output'];
};

export type MakeAdminInput = {
  userId: Scalars['Int64']['input'];
};

export type MakeAdminOrErrorPayload = ErrorPayload | MakeAdminPayload;

export type MakeAdminPayload = {
  __typename?: 'MakeAdminPayload';
  userId: Scalars['Int64']['output'];
};

export type Mutation = {
  __typename?: 'Mutation';
  admin: AdminMutation;
  signOut: SignOutPayload;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  endCursor?: Maybe<Scalars['Int64']['output']>;
  hasNextPage: Scalars['Boolean']['output'];
};

export type Query = {
  __typename?: 'Query';
  admin: AdminQuery;
  viewer: Viewer;
};

export type RemoveAdminInput = {
  userId: Scalars['Int64']['input'];
};

export type RemoveAdminOrErrorPayload = ErrorPayload | RemoveAdminPayload;

export type RemoveAdminPayload = {
  __typename?: 'RemoveAdminPayload';
  userId: Scalars['Int64']['output'];
};

export type SignOutPayload = {
  __typename?: 'SignOutPayload';
  redirectUrl: Scalars['String']['output'];
};

export type Timestamp = {
  __typename?: 'Timestamp';
  formatted: Scalars['String']['output'];
  unix: Scalars['Int64']['output'];
};


export type TimestampformattedArgs = {
  layout?: Scalars['String']['input'];
};

export type UnbanUserInput = {
  userId: Scalars['Int64']['input'];
};

export type UnbanUserOrErrorPayload = ErrorPayload | UnbanUserPayload;

export type UnbanUserPayload = {
  __typename?: 'UnbanUserPayload';
  userId: Scalars['Int64']['output'];
};

export type User = {
  __typename?: 'User';
  createdAt: Timestamp;
  email: Scalars['String']['output'];
  id: Scalars['Int64']['output'];
  name: Scalars['String']['output'];
};

export type UsersConnection = {
  __typename?: 'UsersConnection';
  nodes: Array<AdminUser>;
  totalCount: Scalars['Int64']['output'];
};

export type Viewer = {
  __typename?: 'Viewer';
  role: ViewerRole;
  user?: Maybe<User>;
};

export enum ViewerRole {
  ADMIN = 'ADMIN',
  GUEST = 'GUEST',
  USER = 'USER'
}


}
