// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_users_show_banMutationVariables = Exact<{
  input: BanUserInput;
}>;


export type starterkit_users_show_banMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', banUser: { __typename: 'BanUserPayload', userId: number } | { __typename: 'ErrorPayload', message: string, byFields: Array<{ __typename?: 'FieldMessage', name: string, value: string }> } } };


export function $starterkit_users_show_ban(variables: starterkit_users_show_banMutationVariables, opts?: { revalidate?: boolean }): starterkit_users_show_banMutation {
	return $starterkit_gql_request(`mutation starterkit_users_show_ban(\u0024input: BanUserInput!) {
  admin {
    banUser(input: \u0024input) {
      __typename
      ... on BanUserPayload {
        userId
      }
      ... on ErrorPayload {
        message
        byFields {
          name
          value
        }
      }
    }
  }
}`, variables, opts) as starterkit_users_show_banMutation
}

}
