// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_users_show_dataQueryVariables = Exact<{
  id: Scalars['Int64']['input'];
}>;


export type starterkit_users_show_dataQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', user?: { __typename?: 'AdminUser', id: number, email: string, name: string, isAdmin: boolean, banReason: string, createdAt: { __typename?: 'Timestamp', formatted: string }, lastSignInAt?: { __typename?: 'Timestamp', unix: number, formatted: string } | null } | null } };


export function $starterkit_users_show_data(variables: starterkit_users_show_dataQueryVariables, opts?: { revalidate?: boolean }): starterkit_users_show_dataQuery {
	return $starterkit_gql_request(`query starterkit_users_show_data(\u0024id: Int64!) {
  admin {
    user(id: \u0024id) {
      id
      email
      name
      createdAt {
        formatted
      }
      lastSignInAt {
        unix
        formatted
      }
      isAdmin
      banReason
    }
  }
}`, variables, opts) as starterkit_users_show_dataQuery
}

}
