// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_users_show_make_adminMutationVariables = Exact<{
  input: MakeAdminInput;
}>;


export type starterkit_users_show_make_adminMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', makeAdmin: { __typename: 'ErrorPayload', message: string, byFields: Array<{ __typename?: 'FieldMessage', name: string, value: string }> } | { __typename: 'MakeAdminPayload', userId: number } } };


export function $starterkit_users_show_make_admin(variables: starterkit_users_show_make_adminMutationVariables, opts?: { revalidate?: boolean }): starterkit_users_show_make_adminMutation {
	return $starterkit_gql_request(`mutation starterkit_users_show_make_admin(\u0024input: MakeAdminInput!) {
  admin {
    makeAdmin(input: \u0024input) {
      __typename
      ... on MakeAdminPayload {
        userId
      }
      ... on ErrorPayload {
        message
        byFields {
          name
          value
        }
      }
    }
  }
}`, variables, opts) as starterkit_users_show_make_adminMutation
}

}
