// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_users_show_remove_adminMutationVariables = Exact<{
  input: RemoveAdminInput;
}>;


export type starterkit_users_show_remove_adminMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', removeAdmin: { __typename: 'ErrorPayload', message: string, byFields: Array<{ __typename?: 'FieldMessage', name: string, value: string }> } | { __typename: 'RemoveAdminPayload', userId: number } } };


export function $starterkit_users_show_remove_admin(variables: starterkit_users_show_remove_adminMutationVariables, opts?: { revalidate?: boolean }): starterkit_users_show_remove_adminMutation {
	return $starterkit_gql_request(`mutation starterkit_users_show_remove_admin(\u0024input: RemoveAdminInput!) {
  admin {
    removeAdmin(input: \u0024input) {
      __typename
      ... on RemoveAdminPayload {
        userId
      }
      ... on ErrorPayload {
        message
        byFields {
          name
          value
        }
      }
    }
  }
}`, variables, opts) as starterkit_users_show_remove_adminMutation
}

}
