// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type starterkit_users_show_unbanMutationVariables = Exact<{
  input: UnbanUserInput;
}>;


export type starterkit_users_show_unbanMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', unbanUser: { __typename: 'ErrorPayload', message: string, byFields: Array<{ __typename?: 'FieldMessage', name: string, value: string }> } | { __typename: 'UnbanUserPayload', userId: number } } };


export function $starterkit_users_show_unban(variables: starterkit_users_show_unbanMutationVariables, opts?: { revalidate?: boolean }): starterkit_users_show_unbanMutation {
	return $starterkit_gql_request(`mutation starterkit_users_show_unban(\u0024input: UnbanUserInput!) {
  admin {
    unbanUser(input: \u0024input) {
      __typename
      ... on UnbanUserPayload {
        userId
      }
      ... on ErrorPayload {
        message
        byFields {
          name
          value
        }
      }
    }
  }
}`, variables, opts) as starterkit_users_show_unbanMutation
}

}
