package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"starterkit/internal/appreq"
	"starterkit/internal/db"
	"starterkit/internal/graph/generated"
	"starterkit/internal/graph/model"
	model1 "starterkit/internal/model"

	"github.com/vektah/gqlparser/v2/ast"
)

// BanUser is the resolver for the banUser field.
func (r *adminMutationResolver) BanUser(ctx context.Context, obj *model1.AdminMutation, input model.BanUserInput) (model.BanUserOrErrorPayload, error) {
	return r.env(ctx).BanUser(ctx, input)
}

// UnbanUser is the resolver for the unbanUser field.
func (r *adminMutationResolver) UnbanUser(ctx context.Context, obj *model1.AdminMutation, input model.UnbanUserInput) (model.UnbanUserOrErrorPayload, error) {
	return r.env(ctx).UnbanUser(ctx, input)
}

// MakeAdmin is the resolver for the makeAdmin field.
func (r *adminMutationResolver) MakeAdmin(ctx context.Context, obj *model1.AdminMutation, input model.MakeAdminInput) (model.MakeAdminOrErrorPayload, error) {
	return r.env(ctx).MakeAdmin(ctx, input)
}

// RemoveAdmin is the resolver for the removeAdmin field.
func (r *adminMutationResolver) RemoveAdmin(ctx context.Context, obj *model1.AdminMutation, input model.RemoveAdminInput) (model.RemoveAdminOrErrorPayload, error) {
	return r.env(ctx).RemoveAdmin(ctx, input)
}

// Users is the resolver for the users field.
func (r *adminQueryResolver) Users(ctx context.Context, obj *model1.AdminQuery) (*model.UsersConnection, error) {
	return &model.UsersConnection{}, nil
}

// User is the resolver for the user field.
func (r *adminQueryResolver) User(ctx context.Context, obj *model1.AdminQuery, id int64) (*db.DBListUsersRow, error) {
	row, err := r.env(ctx).DBGetAdminUserByID(ctx, id)
	if db.IsNotFound(err) {
		return nil, nil
	}

	if err != nil {
		return nil, fmt.Errorf("failed to load user %d: %w", id, err)
	}

	bound := adminUserRow(row)

	return &bound, nil
}

// Admins is the resolver for the admins field.
func (r *adminQueryResolver) Admins(ctx context.Context, obj *model1.AdminQuery) (*model.AdminsConnection, error) {
	return &model.AdminsConnection{}, nil
}

// AuditLog is the resolver for the auditLog field.
func (r *adminQueryResolver) AuditLog(ctx context.Context, obj *model1.AdminQuery, limit int64, before *int64) (*model.AuditLogConnection, error) {
	return r.env(ctx).ListAuditLog(ctx, limit, before)
}

// BuildGitCommit is the resolver for the buildGitCommit field.
func (r *adminQueryResolver) BuildGitCommit(ctx context.Context, obj *model1.AdminQuery) (string, error) {
	return r.env(ctx).BuildGitCommit(), nil
}

// IsAdmin is the resolver for the isAdmin field.
func (r *adminUserResolver) IsAdmin(ctx context.Context, obj *db.DBListUsersRow) (bool, error) {
	return obj.IsAdmin != 0, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *adminsConnectionResolver) TotalCount(ctx context.Context, obj *model.AdminsConnection) (int64, error) {
	count, err := r.env(ctx).DBCountAdmins(ctx)
	if err != nil {
		return 0, fmt.Errorf("failed to count admins: %w", err)
	}

	return count, nil
}

// Nodes is the resolver for the nodes field.
func (r *adminsConnectionResolver) Nodes(ctx context.Context, obj *model.AdminsConnection) ([]db.DBListAdminsRow, error) {
	rows, err := r.env(ctx).DBListAdmins(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list admins: %w", err)
	}

	return rows, nil
}

// SignOut is the resolver for the signOut field.
func (r *mutationResolver) SignOut(ctx context.Context) (*model.SignOutPayload, error) {
	env := r.env(ctx)
	env.RecordSignOut(ctx)

	return &model.SignOutPayload{RedirectURL: env.SignOutURL()}, nil
}

// Admin is the resolver for the admin field.
func (r *mutationResolver) Admin(ctx context.Context) (*model1.AdminMutation, error) {
	err := r.checkAdmin(ctx, ast.Mutation)
	if err != nil {
		return nil, err
	}

	return &model1.AdminMutation{}, nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model1.Viewer, error) {
	return &model1.Viewer{}, nil
}

// Admin is the resolver for the admin field.
func (r *queryResolver) Admin(ctx context.Context) (*model1.AdminQuery, error) {
	err := r.checkAdmin(ctx, ast.Query)
	if err != nil {
		return nil, err
	}

	return &model1.AdminQuery{}, nil
}

// TotalCount is the resolver for the totalCount field.
func (r *usersConnectionResolver) TotalCount(ctx context.Context, obj *model.UsersConnection) (int64, error) {
	count, err := r.env(ctx).DBCountUsers(ctx)
	if err != nil {
		return 0, fmt.Errorf("failed to count users: %w", err)
	}

	return count, nil
}

// Nodes is the resolver for the nodes field.
func (r *usersConnectionResolver) Nodes(ctx context.Context, obj *model.UsersConnection) ([]db.DBListUsersRow, error) {
	rows, err := r.env(ctx).DBListUsers(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %w", err)
	}

	return rows, nil
}

// User is the resolver for the user field.
func (r *viewerResolver) User(ctx context.Context, obj *model1.Viewer) (*db.User, error) {
	return r.env(ctx).CurrentUser(ctx), nil
}

// Role is the resolver for the role field.
func (r *viewerResolver) Role(ctx context.Context, obj *model1.Viewer) (model.ViewerRole, error) {
	req, err := appreq.FromCtx(ctx)
	if err != nil || req.UserID() == nil {
		return model.ViewerRoleGuest, nil
	}

	if req.IsAdmin() {
		return model.ViewerRoleAdmin, nil
	}

	return model.ViewerRoleUser, nil
}

// AdminMutation returns generated.AdminMutationResolver implementation.
func (r *Resolver) AdminMutation() generated.AdminMutationResolver { return &adminMutationResolver{r} }

// AdminQuery returns generated.AdminQueryResolver implementation.
func (r *Resolver) AdminQuery() generated.AdminQueryResolver { return &adminQueryResolver{r} }

// AdminUser returns generated.AdminUserResolver implementation.
func (r *Resolver) AdminUser() generated.AdminUserResolver { return &adminUserResolver{r} }

// AdminsConnection returns generated.AdminsConnectionResolver implementation.
func (r *Resolver) AdminsConnection() generated.AdminsConnectionResolver {
	return &adminsConnectionResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// UsersConnection returns generated.UsersConnectionResolver implementation.
func (r *Resolver) UsersConnection() generated.UsersConnectionResolver {
	return &usersConnectionResolver{r}
}

// Viewer returns generated.ViewerResolver implementation.
func (r *Resolver) Viewer() generated.ViewerResolver { return &viewerResolver{r} }

type (
	adminMutationResolver    struct{ *Resolver }
	adminQueryResolver       struct{ *Resolver }
	adminUserResolver        struct{ *Resolver }
	adminsConnectionResolver struct{ *Resolver }
	mutationResolver         struct{ *Resolver }
	queryResolver            struct{ *Resolver }
	usersConnectionResolver  struct{ *Resolver }
	viewerResolver           struct{ *Resolver }
)
