// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package metrics_test

import (
	"context"
	"starterkit/internal/metrics"
	"sync"
)

// Ensure, that EnvMock does implement metrics.Env.
// If this is not the case, regenerate this file with moq.
var _ metrics.Env = &EnvMock{}

// EnvMock is a mock implementation of metrics.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked metrics.Env
//		mockedEnv := &EnvMock{
//			TableRowCountsFunc: func(ctx context.Context) (map[string]int64, error) {
//				panic("mock out the TableRowCounts method")
//			},
//		}
//
//		// use mockedEnv in code that requires metrics.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// TableRowCountsFunc mocks the TableRowCounts method.
	TableRowCountsFunc func(ctx context.Context) (map[string]int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// TableRowCounts holds details about calls to the TableRowCounts method.
		TableRowCounts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockTableRowCounts sync.RWMutex
}

// TableRowCounts calls TableRowCountsFunc.
func (mock *EnvMock) TableRowCounts(ctx context.Context) (map[string]int64, error) {
	if mock.TableRowCountsFunc == nil {
		panic("EnvMock.TableRowCountsFunc: method is nil but Env.TableRowCounts was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockTableRowCounts.Lock()
	mock.calls.TableRowCounts = append(mock.calls.TableRowCounts, callInfo)
	mock.lockTableRowCounts.Unlock()
	return mock.TableRowCountsFunc(ctx)
}

// TableRowCountsCalls gets all the calls that were made to TableRowCounts.
// Check the length with:
//
//	len(mockedEnv.TableRowCountsCalls())
func (mock *EnvMock) TableRowCountsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockTableRowCounts.RLock()
	calls = mock.calls.TableRowCounts
	mock.lockTableRowCounts.RUnlock()
	return calls
}
