// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"starterkit/internal/dbtime"
)

type Admin struct {
	UserID    int64        `json:"user_id"`
	CreatedAt dbtime.Stamp `json:"created_at"`
}

type AuditLog struct {
	ID        int64        `json:"id"`
	UserID    *int64       `json:"user_id"`
	Email     string       `json:"email"`
	Action    string       `json:"action"`
	Detail    string       `json:"detail"`
	Ip        string       `json:"ip"`
	CreatedAt dbtime.Stamp `json:"created_at"`
}

type Goqite struct {
	ID       string `json:"id"`
	Created  string `json:"created"`
	Updated  string `json:"updated"`
	Queue    string `json:"queue"`
	Body     []byte `json:"body"`
	Timeout  string `json:"timeout"`
	Received int64  `json:"received"`
	Priority int64  `json:"priority"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type User struct {
	ID           int64         `json:"id"`
	OidcIssuer   string        `json:"oidc_issuer"`
	OidcSubject  string        `json:"oidc_subject"`
	Email        string        `json:"email"`
	Name         string        `json:"name"`
	LastSigninAt *dbtime.Stamp `json:"last_signin_at"`
	CreatedAt    dbtime.Stamp  `json:"created_at"`
}

type UserBan struct {
	UserID    int64        `json:"user_id"`
	BannedBy  *int64       `json:"banned_by"`
	Reason    string       `json:"reason"`
	CreatedAt dbtime.Stamp `json:"created_at"`
}
