// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.write.sql

package db

import (
	"context"

	"starterkit/internal/dbtime"
)

const dBDeleteAdmin = `-- name: DBDeleteAdmin :execrows
delete from admins
 where admins.user_id = ?
   and (select count(*) from admins) > 1
`

func (q *WriteQueries) DBDeleteAdmin(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, dBDeleteAdmin, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dBDeleteAuditLogBefore = `-- name: DBDeleteAuditLogBefore :exec
delete from audit_log where created_at < ?
`

func (q *WriteQueries) DBDeleteAuditLogBefore(ctx context.Context, createdAt dbtime.Stamp) error {
	_, err := q.db.ExecContext(ctx, dBDeleteAuditLogBefore, createdAt)
	return err
}

const dBDeleteUserBan = `-- name: DBDeleteUserBan :exec
delete from user_bans where user_id = ?
`

func (q *WriteQueries) DBDeleteUserBan(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, dBDeleteUserBan, userID)
	return err
}

const dBInsertAdmin = `-- name: DBInsertAdmin :exec
insert into admins (user_id, created_at) values (?, ?) on conflict(user_id) do nothing
`

type DBInsertAdminParams struct {
	UserID    int64        `json:"user_id"`
	CreatedAt dbtime.Stamp `json:"created_at"`
}

func (q *WriteQueries) DBInsertAdmin(ctx context.Context, arg DBInsertAdminParams) error {
	_, err := q.db.ExecContext(ctx, dBInsertAdmin, arg.UserID, arg.CreatedAt)
	return err
}

const dBInsertAuditLog = `-- name: DBInsertAuditLog :exec
insert into audit_log (user_id, email, action, detail, ip, created_at)
values (?, ?, ?, ?, ?, ?)
`

type DBInsertAuditLogParams struct {
	UserID    *int64       `json:"user_id"`
	Email     string       `json:"email"`
	Action    string       `json:"action"`
	Detail    string       `json:"detail"`
	Ip        string       `json:"ip"`
	CreatedAt dbtime.Stamp `json:"created_at"`
}

func (q *WriteQueries) DBInsertAuditLog(ctx context.Context, arg DBInsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, dBInsertAuditLog,
		arg.UserID,
		arg.Email,
		arg.Action,
		arg.Detail,
		arg.Ip,
		arg.CreatedAt,
	)
	return err
}

const dBInsertUserBan = `-- name: DBInsertUserBan :one
insert into user_bans (user_id, banned_by, reason, created_at)
values (?, ?, ?, ?)
on conflict(user_id) do update set reason = excluded.reason
returning user_id, banned_by, reason, created_at
`

type DBInsertUserBanParams struct {
	UserID    int64        `json:"user_id"`
	BannedBy  *int64       `json:"banned_by"`
	Reason    string       `json:"reason"`
	CreatedAt dbtime.Stamp `json:"created_at"`
}

func (q *WriteQueries) DBInsertUserBan(ctx context.Context, arg DBInsertUserBanParams) (UserBan, error) {
	row := q.db.QueryRowContext(ctx, dBInsertUserBan,
		arg.UserID,
		arg.BannedBy,
		arg.Reason,
		arg.CreatedAt,
	)
	var i UserBan
	err := row.Scan(
		&i.UserID,
		&i.BannedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const dBMarkSignIn = `-- name: DBMarkSignIn :execrows
update users
   set last_signin_at = ?1
 where users.id = ?2
   and (users.last_signin_at is null or users.last_signin_at < ?1)
`

type DBMarkSignInParams struct {
	IssuedAt *dbtime.Stamp `json:"issued_at"`
	ID       int64         `json:"id"`
}

func (q *WriteQueries) DBMarkSignIn(ctx context.Context, arg DBMarkSignInParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, dBMarkSignIn, arg.IssuedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dBUpsertUserByOIDC = `-- name: DBUpsertUserByOIDC :one
insert into users (oidc_issuer, oidc_subject, email, name, last_signin_at, created_at)
values (?, ?, ?, ?, ?, ?)
on conflict(oidc_issuer, oidc_subject) do update set
  email = excluded.email,
  name = excluded.name,
  last_signin_at = excluded.last_signin_at
returning id, oidc_issuer, oidc_subject, email, name, last_signin_at, created_at
`

type DBUpsertUserByOIDCParams struct {
	OidcIssuer   string        `json:"oidc_issuer"`
	OidcSubject  string        `json:"oidc_subject"`
	Email        string        `json:"email"`
	Name         string        `json:"name"`
	LastSigninAt *dbtime.Stamp `json:"last_signin_at"`
	CreatedAt    dbtime.Stamp  `json:"created_at"`
}

func (q *WriteQueries) DBUpsertUserByOIDC(ctx context.Context, arg DBUpsertUserByOIDCParams) (User, error) {
	row := q.db.QueryRowContext(ctx, dBUpsertUserByOIDC,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.Email,
		arg.Name,
		arg.LastSigninAt,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.LastSigninAt,
		&i.CreatedAt,
	)
	return i, err
}

type WriteQueries struct {
	*Queries
}

func NewWriteQueries(db DBTX) *WriteQueries {
	return &WriteQueries{
		Queries: New(db),
	}
}
