// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.read.sql

package db

import (
	"context"

	"starterkit/internal/dbtime"
)

const dBCountAdmins = `-- name: DBCountAdmins :one
select count(*) from admins
`

func (q *Queries) DBCountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dBCountAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dBCountAuditLog = `-- name: DBCountAuditLog :one
select count(*) from audit_log
`

func (q *Queries) DBCountAuditLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dBCountAuditLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dBCountUsers = `-- name: DBCountUsers :one
select count(*) from users
`

func (q *Queries) DBCountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dBCountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dBGetAdminByUserID = `-- name: DBGetAdminByUserID :one
select user_id, created_at from admins where user_id = ?
`

func (q *Queries) DBGetAdminByUserID(ctx context.Context, userID int64) (Admin, error) {
	row := q.db.QueryRowContext(ctx, dBGetAdminByUserID, userID)
	var i Admin
	err := row.Scan(&i.UserID, &i.CreatedAt)
	return i, err
}

const dBGetAdminUserByID = `-- name: DBGetAdminUserByID :one
select u.id,
       u.email,
       u.name,
       u.created_at,
       u.last_signin_at,
       case when a.user_id is null then 0 else 1 end as is_admin,
       coalesce(b.reason, '') as ban_reason
  from users u
  left join admins a on a.user_id = u.id
  left join user_bans b on b.user_id = u.id
 where u.id = ?
`

type DBGetAdminUserByIDRow struct {
	ID           int64         `json:"id"`
	Email        string        `json:"email"`
	Name         string        `json:"name"`
	CreatedAt    dbtime.Stamp  `json:"created_at"`
	LastSigninAt *dbtime.Stamp `json:"last_signin_at"`
	IsAdmin      int64         `json:"is_admin"`
	BanReason    string        `json:"ban_reason"`
}

func (q *Queries) DBGetAdminUserByID(ctx context.Context, id int64) (DBGetAdminUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, dBGetAdminUserByID, id)
	var i DBGetAdminUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSigninAt,
		&i.IsAdmin,
		&i.BanReason,
	)
	return i, err
}

const dBGetIdentityByOIDC = `-- name: DBGetIdentityByOIDC :one
select u.id,
       u.email,
       u.name,
       u.created_at,
       u.last_signin_at,
       case when a.user_id is null then 0 else 1 end as is_admin,
       coalesce(b.reason, '') as ban_reason
  from users u
  left join admins a on a.user_id = u.id
  left join user_bans b on b.user_id = u.id
 where u.oidc_issuer = ? and u.oidc_subject = ?
`

type DBGetIdentityByOIDCParams struct {
	OidcIssuer  string `json:"oidc_issuer"`
	OidcSubject string `json:"oidc_subject"`
}

type DBGetIdentityByOIDCRow struct {
	ID           int64         `json:"id"`
	Email        string        `json:"email"`
	Name         string        `json:"name"`
	CreatedAt    dbtime.Stamp  `json:"created_at"`
	LastSigninAt *dbtime.Stamp `json:"last_signin_at"`
	IsAdmin      int64         `json:"is_admin"`
	BanReason    string        `json:"ban_reason"`
}

func (q *Queries) DBGetIdentityByOIDC(ctx context.Context, arg DBGetIdentityByOIDCParams) (DBGetIdentityByOIDCRow, error) {
	row := q.db.QueryRowContext(ctx, dBGetIdentityByOIDC, arg.OidcIssuer, arg.OidcSubject)
	var i DBGetIdentityByOIDCRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastSigninAt,
		&i.IsAdmin,
		&i.BanReason,
	)
	return i, err
}

const dBGetUserBan = `-- name: DBGetUserBan :one
select user_id, banned_by, reason, created_at from user_bans where user_id = ?
`

func (q *Queries) DBGetUserBan(ctx context.Context, userID int64) (UserBan, error) {
	row := q.db.QueryRowContext(ctx, dBGetUserBan, userID)
	var i UserBan
	err := row.Scan(
		&i.UserID,
		&i.BannedBy,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const dBGetUserByID = `-- name: DBGetUserByID :one
select id, oidc_issuer, oidc_subject, email, name, last_signin_at, created_at from users where id = ?
`

func (q *Queries) DBGetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, dBGetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.Name,
		&i.LastSigninAt,
		&i.CreatedAt,
	)
	return i, err
}

const dBListAdmins = `-- name: DBListAdmins :many
select a.user_id, a.created_at, u.email, u.name
  from admins a
  join users u on u.id = a.user_id
 order by a.created_at desc
`

type DBListAdminsRow struct {
	UserID    int64        `json:"user_id"`
	CreatedAt dbtime.Stamp `json:"created_at"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
}

func (q *Queries) DBListAdmins(ctx context.Context) ([]DBListAdminsRow, error) {
	rows, err := q.db.QueryContext(ctx, dBListAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DBListAdminsRow
	for rows.Next() {
		var i DBListAdminsRow
		if err := rows.Scan(
			&i.UserID,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dBListAuditLog = `-- name: DBListAuditLog :many
select id, user_id, email, "action", detail, ip, created_at from audit_log
 where (id < ?1 or ?1 = 0)
 order by id desc
 limit ?2
`

type DBListAuditLogParams struct {
	Before    int64 `json:"before"`
	PageLimit int64 `json:"page_limit"`
}

func (q *Queries) DBListAuditLog(ctx context.Context, arg DBListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, dBListAuditLog, arg.Before, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Action,
			&i.Detail,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dBListUsers = `-- name: DBListUsers :many
select u.id,
       u.email,
       u.name,
       u.created_at,
       u.last_signin_at,
       case when a.user_id is null then 0 else 1 end as is_admin,
       coalesce(b.reason, '') as ban_reason
  from users u
  left join admins a on a.user_id = u.id
  left join user_bans b on b.user_id = u.id
 order by u.id
`

type DBListUsersRow struct {
	ID           int64         `json:"id"`
	Email        string        `json:"email"`
	Name         string        `json:"name"`
	CreatedAt    dbtime.Stamp  `json:"created_at"`
	LastSigninAt *dbtime.Stamp `json:"last_signin_at"`
	IsAdmin      int64         `json:"is_admin"`
	BanReason    string        `json:"ban_reason"`
}

func (q *Queries) DBListUsers(ctx context.Context) ([]DBListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, dBListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DBListUsersRow
	for rows.Next() {
		var i DBListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.LastSigninAt,
			&i.IsAdmin,
			&i.BanReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
